### ISSUE TITLE
Python3 package?

### ISSUE THREAD

**Issue by LocutusOfBorg** [vulndb/python-sdk#14]
Hello, in Debian we are dropping Python2 from next stable...
bugs.debian.org/938253

**Comment by andresriancho** [comment]
Thanks for reporting this.

Fixed in latest pypi release https://pypi.org/project/vulndb/0.1.3/ and also in master. The tool now supports both 2 and 3.

**Comment by LocutusOfBorg** [comment]
Shouldn't then the setup.py file also list Python3 then?

**Comment by LocutusOfBorg** [comment]
thanks for fixing!

**Comment by LocutusOfBorg** [comment]
got it, looks like this git repo is outdated!

**Comment by andresriancho** [comment]
Ah, sorry, forgot to push.

**Comment by andresriancho** [comment]
https://github.com/vulndb/python-sdk/blob/master/setup.py#L43
